apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "releaseName" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "releaseName" . }}
  template:
    metadata:
      labels:
        app: {{ template "releaseName" . }}
    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
          {{- range $key, $val := .Values.secrets }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ template "releaseName" $ }}
                key: {{ $key }}
          {{- end }}
        command: ["/bin/sh", "-c"]
        args: ["ln -sfn /persistantVolume/pythonsqlite.db /pythonsqlite.db && gunicorn3 -w 1 -b 0.0.0.0:5005 kyc:app"]
        volumeMounts:
        - mountPath: /persistantVolume/
          name: storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: {{ .Values.psvClaim.name }}
