apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.storage.className }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.storage.className }}
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - {{ .Values.storage.accessModes }}
  hostPath:
    path: {{ .Values.storage.hostpath }}
