apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.psvClaim.name }}
  namespace: jimber
  annotations:
    helm.sh/resource-policy: "keep"

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.psvClaim.storage }}
  storageClassName: rook-cephfs