apiVersion: v1
kind: Secret
metadata:
  name: {{ template "releaseName" . }}
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | replace ":" "" | b64enc | quote | toString }}
  {{- end}}