name: beta

on:
  push:
    tags:
      - "beta-v[0-9]+.[0-9]+.[0-9]"

env:
  SEED: ${{ secrets.SEED }}
  PASSWORD: ${{ secrets.PASSWORD }}
  TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
  TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
  TWILIO_FROM_NUMBER: ${{ secrets.TWILIO_FROM_NUMBER }}
  MESSAGING_SERVICE_SID: ${{ secrets.MESSAGING_SERVICE_SID }}
  SHUFTI_CLIENT_ID: ${{ secrets.SHUFTI_CLIENT_ID }}
  SHUFTI_SECRET_ID: ${{ secrets.SHUFTI_SECRET_ID }}
  SHUFTI_REQUEST_LIMIT: 5
  URL: "https://login-beta.jimbertesting.be"
  IMAGE_NAME: threefoldjimber/openkyc

jobs:
  build_kyc:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.image.outputs.lowercase }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: image
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}

      - name: Build and push
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:beta-${{ github.sha }},${{ env.IMAGE_NAME }}:beta-latest
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: [build_kyc]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create kubeconfig
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.BETA_KUBE_KEY }} | base64 --decode > ${HOME}/.kube/jimber-beta.key
          echo ${{ secrets.BETA_KUBE_CRT }} | base64 --decode > ${HOME}/.kube/jimber-beta.crt
          echo ${{ secrets.BETA_KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
          echo $(ls ${HOME}/.kube)
      - name: Upgrade beta on cluster
        run: |
          helm upgrade --install -n jimber beta-openkyc helm_files -f helm_files/values/values-beta.yaml \
          --set global.IMAGE=threefoldjimber/openkyc:beta-${{ github.sha }} \
          --set global.TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN \
          --set global.TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID \
          --set global.PASSWORD=$PASSWORD \
          --set global.SEED=$SEED \
          --set global.MESSAGING_SERVICE_SID=$MESSAGING_SERVICE_SID \
          --set global.SHUFTI_CLIENT_ID=$SHUFTI_CLIENT_ID \
          --set global.SHUFTI_SECRET_ID=$SHUFTI_SECRET_ID \
          --set global.TWILIO_FROM_NUMBER="$TWILIO_FROM_NUMBER" 
